<?php

/**
 * @file
 * Contains install and update for Varbase Style guide module.
 */

use Drupal\Core\Recipe\Recipe;
use Drupal\Core\Recipe\RecipeRunner;

/**
 * Implements hook_install().
 */
function varbase_styleguide_install() {

  $default_recipe = Recipe::createFromDirectory(__DIR__ . '/recipes/default');
  RecipeRunner::processRecipe($default_recipe);

}

/**
 * Issue #3272300: Switch to use the Module Installer Factory.
 *
 * In the Varbase Style Guide module.
 */
function varbase_styleguide_update_90001() {
  // Set the weight of the module after installation of list of modules.
  // To make sure that any hook or event subscriber worker after all used modules.
  // No longer needed, as switched to dependencies and recipes.
}
